// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function getMigrationDatabaseUrl() {
  return process.env.DIRECT_URL?.trim() || process.env.DATABASE_URL?.trim();
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "pnpm tsx prisma/seed.ts",
  },
  datasource: {
    url: getMigrationDatabaseUrl(),
  },
});
