import { Toaster } from "@/components/ui/sonner";
import { fontVariables } from "@/config/font.config";
import { cn } from "@/lib/utils";
import Providers from "@/theme/providers";
import { ThemeProvider } from "@/theme/theme-provider";
import { DEFAULT_THEME, THEMES } from "@/theme/theme.config";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import "../styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const activeThemeValue = cookieStore.get("active_theme")?.value;
  const isValidTheme = THEMES.some((t) => t.value === activeThemeValue);
  const themeToApply = isValidTheme ? activeThemeValue! : DEFAULT_THEME;
  return (
    <html lang="en" suppressHydrationWarning data-theme={themeToApply}>
      <head />
      <body
        className={cn(
          "bg-background overflow-x-hidden overscroll-none font-sans antialiased",
          fontVariables,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers activeThemeValue={themeToApply}>
            <Toaster position="top-right" />
            {children}
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
